version: "3.8"

services:
  ctracker_server:
    container_name: ctracker_server
    build: .
    command: python manage.py runserver --nostatic 0.0.0.0:8000
    volumes:
      - ./data:/code/data
    ports:
      - 8000:8000
  ctracker_poll_unprocessed_notifications:
    container_name: ctracker_poll_unprocessed_notifications
    build: .
    depends_on:
      - ctracker_server
    command: python manage.py poll_unprocessed_notifications --loop --interval 30
    volumes:
      - ./data:/code/data
  ctracker_poll_unnotified_registers:
    container_name: ctracker_poll_unnotified_registers
    build: .
    depends_on:
      - ctracker_server
    command: python manage.py poll_unnotified_registers --loop --interval 60
    volumes:
      - ./data:/code/data
  ctracker_check_enable_notification:
    container_name: ctracker_check_enable_notification
    build: .
    depends_on:
      - ctracker_server
    command: python manage.py check_enable_notification --loop --interval 60
    volumes:
      - ./data:/code/data
