name: front
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^2.1.0
  google_fonts: ^2.0.0
  cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  provider: ^5.0.0
  google_maps_flutter: ^0.5.25+1
  location: ^4.2.0
  flutter_google_places: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - .env

flutter:

  uses-material-design: true

