# Generated by Django 3.0.5 on 2021-04-23 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ctracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaceRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('place_id', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctracker.User')),
            ],
            options={
                'unique_together': {('user', 'place_id', 'arrival_date')},
            },
        ),
    ]
