# Generated by Django 3.0.5 on 2021-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctracker', '0002_userplaceregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaceregister',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userplaceregister',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
