# Generated by Django 3.0.5 on 2021-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctracker', '0004_auto_20210423_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaceregister',
            name='has_to_notify',
            field=models.BooleanField(default=False),
        ),
    ]
