# Generated by Django 3.0.5 on 2021-04-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctracker', '0005_userplaceregister_has_to_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaceregister',
            name='number_of_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
